In [6]:
n=0
while  n<10
  n+=1;
  println(n)
end

1
2
3
4
5
6
7
8
9
10


In [8]:
myFriends = ["a","b","c","d"]
i=1
while i<=length(myFriends)
  friend = myFriends[i];
  println("Hi $friend, whassup");
  i+=1
end

Hi a, whassup
Hi b, whassup
Hi c, whassup
Hi d, whassup


In [9]:
for n in 1:10
  println(n)
end

1
2
3
4
5
6
7
8
9
10


In [10]:
for n in myFriends
  println(n)
end

a
b
c
d


In [12]:
for n = 1:10
  println(n)
end


1
2
3
4
5
6
7
8
9
10


In [14]:
m,n =5, 5
A=zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [17]:
for i in 1:m
  for j in 1:n
    A[i,j]=i+j;
  end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [21]:
B=zeros(m,n)
for i in 1:m, j=1:n
  B[i,j]=i+j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [22]:
for i in 1:m, j=1:n
  C[i,j]=i+j
end
C

UndefVarError: UndefVarError: C not defined

In [24]:
C = [i+j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [26]:
for n in 1:5
  A=[i+j for i in 1:n, j in 1:n]
  display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [29]:
D = fill(0,(3,2))

3×2 Array{Int64,2}:
 0  0
 0  0
 0  0

In [45]:
squares = Dict(1 => 1)

Dict{Int64,Int64} with 1 entry:
  1 => 1

In [46]:
for i in 1:100
  squares[i]=i*i
end

In [47]:
@assert squares[10] == 100

In [59]:
squares_arr = [i*i for i in 1:100]

100-element Array{Int64,1}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [60]:
@assert sum(squares_arr) == 338350

In [76]:
m=3
n=7
DP=ones(m,n)

3×7 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [77]:
for row in 2:m, col in 2:n
  DP[row,col]=DP[row-1,col]+DP[row,col-1]
end

In [78]:
DP

3×7 Array{Float64,2}:
 1.0  1.0  1.0   1.0   1.0   1.0   1.0
 1.0  2.0  3.0   4.0   5.0   6.0   7.0
 1.0  3.0  6.0  10.0  15.0  21.0  28.0

In [79]:
sq = Dict(i => i*i for i in 1:10)

Dict{Int64,Int64} with 10 entries:
  7  => 49
  4  => 16
  9  => 81
  10 => 100
  2  => 4
  3  => 9
  5  => 25
  8  => 64
  6  => 36
  1  => 1